### ISSUE TITLE
Set Up DevOps Continuous Delivery Pipeline

### ISSUE THREAD

**Issue by shanyizhang** [DevOps-Summer21-Customers-Squads/customers#120]
**As a** Developer
**I need** to set up DevOps continuous delivery pipeline in IBM Cloud
**So that** the project will get deployed when the master branch changes

**Assumptions:** 
* We are to build an automated CI/CD DevOps Pipeline

**Acceptance Criteria:**
```
Given DevOps continuous delivery pipeline in IBM Cloud are all set
When the master branch changes
Then the latest version will get deployed on IBM Cloud
```

**Comment by atharshah1** [comment]
I can do this assign me this issue please.
