### ISSUE TITLE
Add Development Stage in the IBM Cloud CD Pipeline

### ISSUE THREAD

**Issue by derekhq123** [DevOps-Summer21-Customers-Squads/customers#124]
**As a** developer
**I need** to add a development stage in the IBM Cloud CD pipeline
**So that** the pipeline will move to development stage if all tdd tests in build stage are passed

**Assumptions:** 
* The build stage passed in the pipeline

**Acceptance Criteria:**
```
Given the CD Pipeline running
When all tdd tests in build stage are passed
Then the pipeline will deploy the product to the development space
```

**Comment by shcai97** [comment]
Done
