### ISSUE TITLE
Use Pylint to check the code

### ISSUE THREAD

**Issue by TengZhang19** [DevOps-Summer21-Customers-Squads/customers#14]
**As a** developer
**I need** to make sure that our code conforms to the PEP8 Python standard using Pylint
**So that** the code could be highly readable and extendable 

**Assumptions:** 
* Code is ready to check before using Pylint.
* Each developer check the code under the same standard.

**Acceptance Criteria:**
```
Given locally developed code is done
When the Pylint reported some errors or inconsistency
Then developers should review and polish the code
```

**Comment by shcai97** [comment]
I believe this one should begin when codes are completed. Or maybe we will use the CI introduced tomorrow to check the code?
