### ISSUE TITLE
Reboot Customer

### ISSUE THREAD

**Issue by joanna15202** [DevOps-Summer21-Customers-Squads/customers#15]
**As a** Customer Service Manager
**I need** the ability to reboot a customer resource that is running
**So that** when something goes wrong, I can reboot the resource to see the latest data.

**Assumptions:** 
* Customer resource exists. 

**Acceptance Criteria:**
```
Given that the customer ID exists 
When I reboot the customer
Then I will see the latest data stored in database
```

**Comment by shcai97** [comment]
Not very clear what rebooting does. Could you explain it more?

**Comment by joanna15202** [comment]
It is a stateful action call that I followed from the lecture. My understanding is that a user can call this API to refresh a resource that he/she is seeing if it not works, and he/she will get the latest data after rebooting.

**Comment by joanna15202** [comment]
Does not require this action in our customer case
