### ISSUE TITLE
Create ./tests folder

### ISSUE THREAD

**Issue by TengZhang19** [DevOps-Summer21-Customers-Squads/customers#17]
**As a** product owner
**I need** to create ./tests folder
**So that** we could put test cases in it in the future

**Assumptions:** 
* There should be test cases for each function, covering as much situations as we could predict.

**Acceptance Criteria:**
```
Given test cases are ready.
When we need to test the code
Then product owner could utilize the test cases inside the folder.

**Comment by shanyizhang** [comment]
Overall skeleton of file content including directories, imports, test class initialization & associated basic testcases, factories, portal etc. under this folder has been built.
