### ISSUE TITLE
Write test cases 

### ISSUE THREAD

**Issue by TengZhang19** [DevOps-Summer21-Customers-Squads/customers#19]
**As a** product owner
**I need** to write test cases
**So that**  we could test our model

**Assumptions:** 
* we need to cover 95% of the cases
* We need to write test cases for each of Create, Read, Update, Delete, List, Query, Action.

**Acceptance Criteria:**
```
Given the ./tests is still empty.
When we finish writing the test cases.
Then we could add them into the ./tests folder.
```

**Comment by shcai97** [comment]
Test cases should be written along with the code in every story. Request Scrum Master to close the issue.

**Comment by TengZhang19** [comment]
Close since it's not needed.
