### ISSUE TITLE
Integrate the Pull Requests with the Slack channel

### ISSUE THREAD

**Issue by shcai97** [DevOps-Summer21-Customers-Squads/customers#53]
**As a** Developer
**I need** to integrate the pull requests with the slack channel
**So that** team members can receive notifications when there are new PRs and commits.

**Assumptions:** 
* The slack channel and GitHub repo have been set up.

**Acceptance Criteria:**
```
Given the Pull Requests integrated with the Slack channel
When new PRs or commits made in the GitHub repo
Then a notification will be given in the Slack channel
```

**Comment by shcai97** [comment]
Subscribed for any new GitHub Pull Requests and Commits in this repository in the #customers channel by

1. Activate GitHub app in Slack
2. In our channel, run `/github subscribe DevOps-Summer21-Customers-Squads/customers` to subscribe all updates in this repo
3. run `/github unsubscribe DevOps-Summer21-Customers-Squads/customers issues` to exclude new issues

**Comment by shanyizhang** [comment]
Github has been integrated in our Slack channel. Issue closed.
