### ISSUE TITLE
Add honcho to requirements.txt

### ISSUE THREAD

**Issue by joanna15202** [DevOps-Summer21-Customers-Squads/customers#59]
**As a** Developer
**I need** to add honcho to the requirement.txt file
**So that** I can start the project by "honcho start"

**Assumptions:** 
* requirement.txt file is existed.

**Acceptance Criteria:**
```
Given that honcho has been added in requirements.txt
When I honcho start
Then the command works
```

**Comment by shanyizhang** [comment]
Requirement fulfilled. Close this Story.
