### ISSUE TITLE
Write BDD Test Scenario for Query Customers

### ISSUE THREAD

**Issue by derekhq123** [DevOps-Summer21-Customers-Squads/customers#68]
**As a** developer
**I need** to write BDD test scenario for query customers
**So that** I can ensure the query feature works from outside in

**Assumptions:** 
* .feature file and accompanying steps.py file is **available**

**Acceptance Criteria:**
```
Given the query feature is available
When I run behave tool
Then the BDD test will pass, and the user will get all the customer information according to the search criteria.
```

**Comment by TengZhang19** [comment]
reopen to apply a fix of merge conflict

**Comment by TengZhang19** [comment]
fixed
